[".config/zsh/.antidote"]
type = "git-repo"
url = "https://github.com/mattmc3/antidote.git"
refreshPeriod = "168h"

[".config/zsh/pure"]
type = "git-repo"
url = "https://github.com/sindresorhus/pure.git"
refreshPeriod = "168h"
