[tools]
go = "latest"
node = "lts"
"npm:@vtsls/language-server" = "latest"
"npm:skills" = "latest"
pnpm = "latest"
python = "latest"
usage = "latest"

[tools.ruby]
version = "latest"
postinstall = "gem install foreman rails rubocop ruby-lsp ruby-lsp-rails"

[tools.rust]
version = "stable"
profile = "default"
components = ["rust-analyzer", "rust-src"]

[settings]
auto_install = true
not_found_auto_install = true
github_attestations = true
idiomatic_version_file_enable_tools = ["go", "node", "python", "ruby", "rust"]
minimum_release_age = "3d"

[settings.github]
use_git_credentials = true

[settings.node]
compile = false
gpg_verify = true

[settings.python]
compile = false

[settings.ruby]
compile = false
