[tools]
go = "latest"
node = "lts"
pnpm = "latest"
python = "latest"
usage = "latest"

[tools.ruby]
version = "latest"
postinstall = "gem install foreman rails rubocop ruby-lsp ruby-lsp-rails"

[tools.rust]
version = "stable"
profile = "default"

[settings]
auto_install = true
not_found_auto_install = true
github_attestations = true
idiomatic_version_file_enable_tools = ["go", "node", "python", "ruby", "rust"]

[settings.node]
compile = false
gpg_verify = true

[settings.python]
compile = false

[settings.ruby]
compile = false
